version: '3.9'
services:
   db:
    container_name: golang-delos-aqua-pg-test-container
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
    # <Port exposed> : < MySQL Port running inside container>
      - '5455:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local